apiVersion: v2
name: ollama-chart
description: A Helm chart for deploying Ollama LLM service
version: 0.1.0

dependencies:
  - name: ollama
    version: "1.43.0"
    repository: "https://helm.otwld.com/"